### ISSUE TITLE
Store more app meta-information

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#832]
I have no idea what information about apps is stored where or how, so many things are already done I guess.
But here is just what I imagine to be sensible meta-information that should come with each app/module:

- [ ] name *(max ~20chars)*
- [ ] version number
- [ ] app-page link
- [ ] category *(free text max ~40chars)*
- [ ] short description *(max ~80chars)*
- [ ] long description *(max ~300chars)*
- [ ] logo image *(min ~128x128px)*
- [ ] screenshots *(max ~3)*
- [ ] running status *(on/off)*
- [ ] updating status *(is it being upgraded)*
- [ ] notification status *(are there any issues)*
- [ ] link to end user documentation (help)
- [ ] link to the upstream homepage project
- [ ] link to the upstream source repository
- [ ] link to the upstream issue tracker
- [ ] license

Some kind of mandatory test to detect missing info seems sensible to me.

**Comment by JoKeyser** [comment]
Just to clarify, when you say 'store', you mean show on the module's Plinth page? Or do you rather mean to unify the available information for each package, without necessarily showing it to users?

**Comment by mray** [comment]
By "store" I mean its general availability in the frontend, probably in some database entry. But I have no clue how FreedomBox keeps meta information, or if it is aggregated in one place. I'm just thinking about what should be present to have the freedom to build any possible UI for a module.

**Comment by JoKeyser** [comment]
That's cool, makes sense to me. I guess it all could be stored in the module database, to be used by any (future) UI.
One more question: What does "support for SSO" mean?

**Comment by jvalleroy** [comment]
I would suggest we look into using AppStream to structure this kind of information:
https://www.freedesktop.org/wiki/Distributions/AppStream/
It would need to be extended to support web applications and other services.
(Somewhat relevant thread: https://lists.freedesktop.org/archives/appstream/2017-March/000156.html)

**Comment by mray** [comment]
@JoKeyser SSO is single sign-on. I think we're about to get this going slowly, not sure about details. Relevant [github issue](https://github.com/freedombox/Plinth/issues/400) and [taiga user story](https://tree.taiga.io/project/freedombox-freedombox/us/32).

**Comment by JoKeyser** [comment]
@jvalleroy Great find; I've never heard of AppStream before, but indeed they seem to solve exactly this kind of problem. And it might be great to might jump on the same train as the Cockpit people, since they're considering this problem too. Not sure how long/detailed all this will be, but I'll read a bit further.

**Comment by JoKeyser** [comment]
I'm trying to clarify and condense some things I've read, while still puzzling the pieces together. Sorry if I repeat obvious points, and please correct me where I misunderstand. Let me know if this is better discussed elsewhere.

*Appstream*  
Appstream provides a format to describe metadata of software components [0]. It considers two kinds of metadata: Upstream metadata that are written by software authors, and Collection metadata that describe (available) packages in a software repository (e.g. in Debian). The latter are at least partially generated automatically (in Debian from APT and appstream generator).

Appstream metadata and tools are already available for >1700 Debian packages; to try it, just install `apt-get install appstream` and do `apt update`. You'll get the command `appstreamcli` [1]. With this you can search packages (e.g. `appstreamcli search owncloud`), or specifically dump all information of a certain package (e.g. `appstreamcli dump owncloud.desktop`). Note Debian uses YAML files instead of XML, but otherwise is the same [5].

Most currently-available Appstream metadata are for desktop apps, for easy-to-use software centers - very much what we're doing for "server stuff". People over at the Cockpit project also want to provide this [2]; actually more generally, not "just" for Debian (they and Appstream are cross-distro). However, it's a recent, open question how to extend the Appstream language to include a *Type* for "server stuff" [3].

*How could Appstream help us (with this issue)?*  
In a sense, Appstream does not yet provide a solution that we can simply adopt - yet it's the closest ongoing effort in that direction. Appstream is more powerful than we strictly need, since it's cross-distro, and we're part of Debian. Thus, we could decide to solve the current issue in a more Debian-specific, and self-hacked way. However, our own solution would also mean our own problems and stuff to maintain, so maybe the more detailed, general solution is worth it.

My current open questions are:
* Can/should we use the Appstream format to describe Plinth modules?
  Or is this rather only for packages, and modules that require multiple packages should be in a meta-package?
* Can/should *all* the information per Plinth module that @mray mentions be included in Appstream format?
  * While many attributes are straight-forward to translate to Appstream, what about:
	* "exotic", but static attributes like 1) support for single sign-on (SSO) or 2) list of ports that need to be forwarded?
	* "real-time"/volatile attributes like 3) running status (on/off), 4) updating status (is it being upgraded?), and 5) notification status (are there any issues?)
* Could we adopt Appstream in incremental steps?
  * In short term, we might use "home-brewed" Appstream(-like) files to bundle metadata about a Plinth module?
	* Maybe we could start with Type generic, maybe with some custom fields? See [4,5].
	* Some info would be fetched from APT, and some manually generated (like the module descriptions etc. from our __init__.py files).
  * In short/medium term, we could ask/help Debian package maintainers to add Collection metadata files.
  * In medium term, we could join/follow Cockpit's efforts to define the Appstream categories for "server stuff" [3].
  * In medium/long term, we could encourage authors of our modules to provide Upstream metadata.

[0] https://www.freedesktop.org/software/appstream/docs/
[1] https://wiki.debian.org/AppStream
[2] https://github.com/cockpit-project/cockpit/wiki/Server-Applications
[3] https://lists.freedesktop.org/archives/appstream/2017-March/000156.html
[4] https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html
[5] https://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html

**Comment by JoKeyser** [comment]
Here's an incomplete, invalid example file, to get a flavor of what we're talking about.
You can even copy this to `/var/cache/app-info/yaml`, and it shows up in `appstreamcli`.

```yaml
---
File: DEP-11
Version: '0.10'
Origin: Filled-in-automatically?
MediaBaseUrl: Freedombox-Foundation server?
---
ID: net.process-one.ejabberd
Icon:
  cached: ejabberd-TODO.png
Name:
  C: Chat server (ejabberd)
Package: ejabberd
Summary:
  C: Jabber/XMPP server for instant messaging and VoIP signalling.
Type: generic
Categories:
  - Chat
  - VoIP
Description:
  C: <p>
     XMPP is an open and standardized communication protocol. Here 
     you can run and configure your XMPP server, called ejabberd.
     </p>
     <p>
     To actually communicate, you can use the web client or any other
     <a href=http://xmpp.org/xmpp-software/clients/ target=_blank\>
     XMPP client</a>.
     </p>
Url:
  homepage: https://process-one.net/en/ejabberd/
  faq: http://example.org/faq
  bugtracker: http://bugs.example.org/report-issue
⁠ProjectLicense:
  GPL-2.0
⁠Priority:
  1
```
